### ISSUE TITLE
Request error: The URL returned a 404 (not found): 

### ISSUE THREAD

**Issue by khraibani** [scyllagroup/UmbracoFlare#2]
Does the package work on umbraco 7.3.6? I am aware that umbraco packages its stated from 7.4, but It did install fine. Associating the account worked fine but when I try to purge I am getting

Request error: The URL returned a 404 (not found): 
backoffice/UmbracoFlare/CloudflareUmbracoApi/GetAllowedDomains

Thanks

**Comment by LoganPeck** [comment]
Hi, make sure that you have the UmbracoFlare.dll in your bin folder. It sounds like that dll is missing. If it is there, try rebuilding your project if you are in Visual Studio, that might fix it. Let me know if this doesn’t help.

Thanks, Logan

**Comment by khraibani** [comment]
Hi, I have checked the date stamp on the [myproject].dll & it was older than the local one, for some reason webdeploy didn't transfer the dll. Thanks for your help great package by the way.
