### ISSUE TITLE
Umbraco as a Service

### ISSUE THREAD

**Issue by clarkd** [scyllagroup/UmbracoFlare#5]
I've managed to install UmbracoFlare and can see the various dashboards, context menus and have also added our API key etc.

However, whenever I go to purge something, nothing is purged. From what I can see this is related to cultures and hostnames - but, even if I add one of these to our root note I can still see that nothing is being purged. It displays a message saying "You have succesfully cleared the cache for this node" however the response to the AJAX call to purge comes back with "0 urls purged successfully."

Additionally if I try to purge something from the UmbracoFlare dashboard, for example Purge by URL, then I see a message saying "You do not have any hostnames registered with Umbraco".

We're actually running on Umbraco as a Service but I don't think this is the issue. Any ideas?

**Comment by clarkd** [comment]
Doh, after adding the hostname to the root node and restarting the web server it's working. :)

**Comment by markadrake** [comment]
@clarkd Thanks for the report! So in the first case when you cleared the cache from the specific content node, we probably should have given you the same error message about the hostnames. I'll bring it up to the team on Tuesday.

**Comment by clarkd** [comment]
Yeah that sounds sensible - I only dug around a little because it the response came back so quickly and then I saw the AJAX response with "0 urls" etc..

**Comment by markadrake** [comment]
@LoganPeck did we resolve this? :)

**Comment by markadrake** [comment]
Hi everyone! Since it's been a while since we last spoke about this issue I'm going to go ahead and close this out. If it becomes an issue again, please open up a new issue and we'll pick it back up. Thanks.
