### ISSUE TITLE
404 on /umbraco/backoffice/UmbracoFlare/CloudflareUmbracoApi/GetAllowedDomains

### ISSUE THREAD

**Issue by leethomascook** [scyllagroup/UmbracoFlare#6]
Hi,

I have installed this on a 7.5.3 installation and I always get a 404 for this request. I have debugged the routing and it seems to be in the dictionary, which is weird.

This request: /umbraco/backoffice/UmbracoFlare/CloudflareUmbracoApi/UpdateConfigStatus

It does return a response, such as: '{"purgeCacheOn":true,"additionalUrls":null,"apiKey":"xx","accountEmail":"xx@xx.xx","credentialsAreValid":true}

But then i get message of: "We could not validate your credentials.', which somewhat contradicts the response.

Thanks,

Lee

**Comment by leethomascook** [comment]
After a bit more debugging, it was related to me having set it to use a camelCase JsonFormatter. This had never affected any other plugins though, which is odd. 

   GlobalConfiguration.Configuration
         .Formatters
         .JsonFormatter
         .SerializerSettings
         .ContractResolver = new CamelCasePropertyNamesContractResolver();

**Comment by leethomascook** [comment]
As a side note, I had to download the source and compile against 7.5.3 to get this to fully work. The version on nuget did not work with 7.5.3.

**Comment by LoganPeck** [comment]
Hi Lee, thanks for the report. Sounds like we have some issues to deal with in 7.5. What did you have to do to get it to compile against 7.5? If its something you would want to send a pull request for that would be great.

Thanks!

**Comment by YodasMyDad** [comment]
Same problem. Get the JS error... Any news on when an updated Nuget package will be done to support v7.5+

**Comment by LoganPeck** [comment]
Sorry it took so long to get up a new version. I just put up a new version for 7.5.6 on Nuget. Let me know if you are still having the same issues.
