### ISSUE TITLE
Doesn't work on umbraco 7.6.1

### ISSUE THREAD

**Issue by khraibani** [scyllagroup/UmbracoFlare#8]
Hi, The package install fine and I can see all the js been loaded in dev tool, but nothing shows on the side menu. Is there much difference between 7.5 and 7.6 for it not to work?

Thanks

**Comment by markadrake** [comment]
Thank you @khraibani. I'm going to test this out asap and get back with you.

**Comment by markadrake** [comment]
Hi @khraibani 

- I installed Umbraco v7.6.4 from Nuget
- Configured and setup a new site from fresh
- Installed UmbracoFlare v1.1.0 Package
- Edited my user account and checked UmbracoFlare
- Refreshed the browser window and UmbracoFlare is now listed

Please let me know if these steps resolve the issue for you!

![image](https://user-images.githubusercontent.com/713355/28236092-cb9455d6-68ea-11e7-8079-8038a89b28be.png)
![image](https://user-images.githubusercontent.com/713355/28236067-25643b36-68ea-11e7-9d05-19d682d7bed8.png)

**Comment by khraibani** [comment]
Thank you that worked! I have missed that you have to add it in users section my bad

**Comment by markadrake** [comment]
Quite alright @khraibani glad we could get it worked out!
